imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

neo4j:
    connections:
        default:
            scheme: http
            host: "%neo4j_host%"
            port: "%neo4j_port%"
            username: "%neo4j_username%"
            password: "%neo4j_password%"

old_sound_rabbit_mq:
    connections:
        default:
            host: "%rabbitmq_host%"
            port: "%rabbitmq_port%"
            user: "%rabbitmq_username%"
            password: "%rabbitmq_password%"
    consumers:
        rabbitmq_simplebus:
            connection: default
            exchange_options: { name: 'sylius_workshop_croatia', type: fanout }
            queue_options: { name: 'sylius_workshop_croatia' }
            callback: rabbitmq_simplebus.consumer
